### PR TITLE
change require to import (fix bundling)

### PR DESCRIPTION
**Pull request by MuraraAllan**
**Title:** 
- convert require to import

**Description:** (optional)
- fix require into import
- Detailed change 2

**Motivation:** (optional)
- the bundling is not working, due to the require statement

**Related Issues:** (optional)
- image

### CODE REVIEW

**Review by roh26it — DISMISSED** [review]

**Comment by roh26it** [comment]
Thanks for catching this @MuraraAllan 

I'm just going to run some tests later today and merge this!

**Comment by VisargD** [comment]
Hey. Thanks for the PR! The husky pre-commit will be useful. Please make the PR ready for review whenever its done. I will merge it in the next release.

**Comment by MuraraAllan** [comment]
done! 
I hope you don't mind a bit more stuff to review. 
I implemented 2 pre hooks, 1 for pre-push too.

We build and halt if something goes wrong with local version. 
Not automated test, but might prevent future incidents!

Sorry for the push force in the fork, not my intention.

**Review by VisargD — APPROVED** [review]

**Comment by MuraraAllan** [comment]
closed in favor of a new signed one

**Pull request closed without merging**
