### PR TITLE
[New Plugin] Medical Advice Detection

### PR DESCRIPTION
**Pull request by Akshay-66**
Plugin Name: **Medical Advice Detection**
Plugin Description: _Detects Medical Advice in the generated response and flags a warning whenever the LLM provides a medical advice._

---

Core logic:
- A simple keyword-based detection mechanism is used in both the request and response stages. If any predefined medical keywords are found, the plugin flags a warning.
- **detectMedicalAdvice()**: Scans the response for medical keywords.
- **detectMedicalRequest()**: Scans the request for medical-related queries.
- **BeforeRequestHook**: Detects whether a user query is likely to lead to medical advice (e.g., checking for keywords like "symptoms" or "diagnose").
- **AfterRequestHook**: Detects medical advice in the LLM's generated response by scanning for medical-related keywords (e.g., "prescribe," "treatment," "medication")

---

**Related Issues:**
- #675 Medical Advice Detection

---

Finally all unit tests pass by running

image

### CODE REVIEW

**Comment by Akshay-66** [comment]
@b4s36t4 @vrushankportkey 
Request for Review / Changes / Approval.

**Review by narengogi — COMMENTED** [review]
Interesting take on a plugin implementation. 
I guess this could be called a generic plugin instead of a medicalkeywords plugin. Because this plugin just invokes a function which is expected to be user defined, 

imo, this should not be in the default plugin category.

**Comment by Akshay-66** [comment]
Thank you @narengogi for your opinion on this, 
It's a great idea to make it as customizable for users for various purposes like medical ,legal and some other privacy / sensitive content / advice (By just changing the keywords given [using it as a template]).

Yes, It just invokes a function, but I'm not aware of more complex logic's and I'm super excited to work on that, can you provide me even more details to improve, like what will be the expectation and result.

Hope you will guide me in the following way.

**Comment by narengogi** [comment]
@b4s36t4 I suggest we close this as not required, what do you think?

**Comment by b4s36t4** [comment]
Yea, we can close this.

**Comment by Akshay-66** [comment]
Ok done, Thanks for your Time and Support.

**Comment by b4s36t4** [comment]
Thanks for your work @Akshay-66. I know this is a bit complicated task and could've been good if it went well. 

If you're up for it you can contribute to new plugins/guardrail, Please try to integrated AWS Bedrock guardrail. 

https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-use-independent-api.html

Please let us know if you're willing to do so, I'll create a new issue and get it assigned to you.

Once again thanks for your contribution :)

**Pull request closed without merging**
