### PR TITLE
Import middleware signed

### PR DESCRIPTION
**Pull request by MuraraAllan**
Title: sign commits
add a || npm format in case of failing to check before commit 

convert require to import
Description: (optional)

fix require into import
Detailed change 2
Motivation: (optional)

the bundling is not working, due to the require statement
Related Issues: (optional)

signed version of #511  , sorry for the oopsie

### CODE REVIEW

**Comment by VisargD** [comment]
Hey. Can you please also push the package-lock updates?

**Comment by MuraraAllan** [comment]
done @VisargD

**Comment by VisargD** [comment]
Hey! Looks like the formatting was not done on the start-test.js file. Can you please check once? Thanks.

**Comment by MuraraAllan** [comment]
Done @VisargD  

My contributions should run smoothly now, I fixed my environment.

**Review by VisargD — APPROVED** [review]

**Pull request merged**
