### PR TITLE
feat: adds ai21 support

### PR DESCRIPTION
**Pull request by rtpa25**

### CODE REVIEW

**Comment by VisargD** [comment]
Hey @rtpa25 , it will be really helpful if you can revert the linting changes in the files.

**Comment by rtpa25** [comment]
bydway just ran ""npm run pretty"" from package.json

**Comment by rtpa25** [comment]
@VisargD edited files still have linting changes.

**Comment by VisargD** [comment]
Thanks for your pull request! Unfortunately, due to significant changes merged since this was opened, we're closing it. Feel free to reopen or create a new PR after updating your branch with the latest changes from main branch.

**Pull request closed without merging**
