### PR TITLE
[Provider] support for AI21 model

### LINKED ISSUE #12: [Provider] Add support for AI21 models
Docs: https://docs.ai21.com/reference/j2-complete-api-ref

### PR DESCRIPTION
**Pull request by kritikash18**
addresses #12

### CODE REVIEW

**Comment by VisargD** [comment]
Thanks @kritikash18 . Will take a look into this.

**Comment by VisargD** [comment]
Hey @kritikash18 , will it be possible for you to also add the support in proxyHandler?

**Comment by kritikash18** [comment]
> Hey @kritikash18 , will it be possible for you to also add the support in proxyHandler?

sure, working on it

**Comment by VisargD** [comment]
Thanks for your pull request! Unfortunately, due to significant changes merged since this was opened, we're closing it. Feel free to reopen or create a new PR after updating your branch with the latest changes from main branch.

**Pull request closed without merging**
