### PR TITLE
Removed compression for node runtime since its buffering the response during streaming

### PR DESCRIPTION
**Pull request by mohankumarelec**
**Title:** 
- Removed compression for node runtime since its buffering the response during streaming

**Description:**
- Removed compression middleware if runtime is node
- Removed content-encoding header to disabled compression for node

**Motivation:**
- Adding compression middleware buffers the response while streaming, defeating the purpose of streaming

**Related Issues:**
- #290

### CODE REVIEW

**Comment by flexchar** [comment]
Actually I am using image where I also disable it. I would propose completely removing it. The benefit is less than the pain it can cause, and in the context of streaming it's not giving much anyways.

**Review by arbi-dev — COMMENTED** [review]
Streaming is very important, please implement this or another fix.

**Comment by VisargD** [comment]
Hey all. I will verify and merge these changes. Thanks for the PR!

**Comment by roh26it** [comment]
@VisargD have we made more changes after this?

**Comment by frunkp** [comment]
@VisargD Can you merge that PR, pretty please 🙏?

**Comment by VisargD** [comment]
@frunkp - Merged the PR. Sorry for the delay on this.

**Comment by frunkp** [comment]
Thank you! Any plans to release `v1.5.4` soon?

**Comment by VisargD** [comment]
Released `v1.5.5` which has this change!

**Pull request merged**
