### PR TITLE
docs: add deploy to Zeabur guide

### LINKED ISSUE #235: Feat: Add Zeabur template for one click deployment
Zeabur is a platform that help you deploy your service with one click, No matter what programming language you use, what framework you use. Add a template for gateway, so that users can do one click gateway deployments.
https://zeabur.com/docs

### PR DESCRIPTION
**Pull request by MichaelYuhe**
**Title:** 
- Add deploy to Zeabur guide.

**Description:** (optional)
- Zeabur is a platform for deploying services easily. I've made a template for everyone to deploy Gateway with one click on Zeabur. Below is the successful deployment.

ai-gateway-running-demo
image

**Motivation:** (optional)
- I just saw that you need help with the self host documentations so I added deploy to Zeabur tutorial into the list

**Related Issues:** (optional)
- #issue-number

### CODE REVIEW

**Comment by vrushankportkey** [comment]
Thank you so much @MichaelYuhe for the contribution! Zeabur looks great

Is it possible to to have the template on a Portkey account on Zeabur? That way, we retain control over how it's deployed. I've tried to copy the "Gateway" template but the website seems to reload.

**Review by vrushankportkey — APPROVED** [review]

**Review by vrushankportkey — COMMENTED** [review]
Should have the template on Portkey account

**Comment by MichaelYuhe** [comment]
Yes of course we can do that, all you need to do is give me the email that used to sign up for Zeabur.
And the deploy bug is fixed now, could you please help me to try it again?

**Comment by vrushankportkey** [comment]
Can you share your Discord or Twitter? Will share the email I used to signup over there

**Comment by MichaelYuhe** [comment]
My Discord account: https://discord.com/users/884404280436588555
Zeabur Discord server: https://discord.gg/7vsCrKrfn5

**Comment by VisargD** [comment]
Closes #235

**Comment by VisargD** [comment]
Closes #222

**Pull request merged**
