### PR TITLE
making options parameter optional

### PR DESCRIPTION
**Pull request by keshavkrishna**
**Title:** 
- making options parameter optional in PluginHandler

**Related Issues:** 
- #708

### CODE REVIEW

**Comment by narengogi** [comment]
I've checked out to this branch, I can still see the same errors

**Review by narengogi — CHANGES_REQUESTED** [review]
I've checked out to this branch, I can still see the same errors after running the tests

**Comment by VisargD** [comment]
Hey @keshavkrishna , were you able to check @narengogi 's comment?

**Comment by keshavkrishna** [comment]
yes I have texted him on discord
Actually the issue he pointed is not in default.tests.ts

**Review by narengogi — APPROVED** [review]
LGTM

**Pull request merged**
